#name: cubie_final
#description: "CUBIE UI - تطبيق القصص التفاعلية للأطفال"
#
#publish_to: 'none'
#
#version: 1.0.0+1
#
#environment:
#  sdk: '>=3.0.0 <4.0.0'
#
#dependencies:
#  flutter:
#    sdk: flutter
#  provider: ^6.0.5
#  http: ^0.13.5
#flutter_blue_plus: ^1.31.20
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  flutter_lints: ^2.0.0
#
#flutter:
#  uses-material-design: true
#  assets:
#    - assets/logo.png
name: cubie_final
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.7
  intl: ^0.19.0

  # --- (التغيير هنا) ---
  # 1. تم حذف flutter_bluetooth_serial
  # 2. تم إضافة flutter_blue_plus
  flutter_blue_plus: ^1.31.20
  permission_handler: ^11.3.1
  # --- (نهاية التغيير) ---

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo2.png